# Generated by Django 2.0.2 on 2018-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
