# Generated by Django 2.0.2 on 2018-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_usertopartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Archive',
            field=models.BooleanField(default=True),
        ),
    ]
