# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catergories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client Name', models.CharField(max_length=150)),
                ('Logo', models.FileField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientToType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Catergories')),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerToClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client')),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerToKiosk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Kiosk')),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('Port', models.IntegerField(primary_key=True, serialize=False, verbose_name='Port')),
                ('Type', models.CharField(choices=[('IPhone', 'IPhone'), ('Android', 'Android'), ('USB-C', 'USB-C'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type Of Charger')),
                ('Kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Kiosk')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeIn', models.DateTimeField(verbose_name='Time In')),
                ('TimeOut', models.DateTimeField(verbose_name='Time Out')),
                ('Port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Port')),
            ],
        ),
        migrations.AddField(
            model_name='kiosk',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.Location'),
        ),
    ]
