# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Logo',
            field=models.FileField(blank=True, null=True, upload_to='logo'),
        ),
    ]
