# Generated by Django 2.0.1 on 2018-02-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='Duration',
            field=models.IntegerField(default=4, verbose_name='Duration'),
            preserve_default=False,
        ),
    ]
