# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20171227_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Client Name',
            new_name='Client_Name',
        ),
    ]
