# Generated by Django 2.0.1 on 2018-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_time_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=1000)),
            ],
        ),
    ]
