# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20171227_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Client_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Location Name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='port',
            name='Type',
            field=models.CharField(choices=[('IPhone', 'IPhone'), ('Android', 'Android'), ('USB-C', 'USB-C'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='TimeIn',
            field=models.DateTimeField(verbose_name='TimeIn'),
        ),
        migrations.AlterField(
            model_name='time',
            name='TimeOut',
            field=models.DateTimeField(verbose_name='TimeOut'),
        ),
    ]
