# Generated by Django 2.0.2 on 2018-07-10 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_auto_20180708_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='User',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='User',
        ),
        migrations.AddField(
            model_name='usertoclient',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client'),
        ),
        migrations.AddField(
            model_name='usertoclient',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
