# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20171227_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Name',
            new_name='ClientName',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='LocationName',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='Partner Name',
            new_name='PartnerName',
        ),
    ]
