# Generated by Django 2.0.2 on 2018-09-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_client_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayCount',
        ),
        migrations.AlterUniqueTogether(
            name='partnertoclient',
            unique_together={('Partner', 'Client')},
        ),
    ]
